dist: jammy
language: python
python: 3.9

install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test

after_success:
  - coveralls

env:
  global:
    - COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  access_key_id: $aws_access_key
  secret_access_key: $aws_secret_access_key
  bucket: $aws_bucket_name
  app: swe-1-hs5544-app
  env: swe-1-hs5544-app
  on:
    repo: hashmmath/hs5544-SWE-App-Task
    branch: main
